name: Backend CI/CD  
  
on:  
  push:  
    branches: [ main ]  
    paths:  
      - 'BE/**'  
  pull_request:  
    branches: [ main ]  
    paths:  
      - 'BE/**'  
  workflow_dispatch:  
  
jobs:  
  build-and-deploy:  
    runs-on: ubuntu-latest  
      
    services:  
      postgres:  
        image: postgres:latest  
        env:  
          POSTGRES_USER: postgres  
          POSTGRES_PASSWORD: 123  
          POSTGRES_DB: postgres  
        ports:  
          - 5432:5432  
        options: >-  
          --health-cmd pg_isready  
          --health-interval 10s  
          --health-timeout 5s  
          --health-retries 5  
      
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  
          
      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.10.11'  
          cache: 'pip'  
          cache-dependency-path: './BE/requirements.txt'  
            
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install flake8 pytest  
          pip install -r BE/requirements.txt  
            
      - name: Lint with flake8  
        run: |  
          flake8 BE --count --select=E9,F63,F7,F82 --show-source --statistics  
          flake8 BE --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  
        
      - name: Run database migrations  
        run: |  
          cd BE  
          alembic upgrade head  
        env:  
          DATABASE_URL: postgresql://postgres:123@localhost:5432/postgres