name: Backend CI/CD  
  
on:  
  push:  
    branches: [ main ]  
    paths:  
      - 'BE/**'  
  pull_request:  
    branches: [ main ]  
    paths:  
      - 'BE/**'  
  workflow_dispatch:  
  
jobs:  
  build-and-deploy:  
    runs-on: ubuntu-latest  
      
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  
          
      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.10.11'  
          cache: 'pip'  
          cache-dependency-path: './BE/requirements.txt'  
            
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install flake8 pytest  
          pip install -r BE/requirements.txt  
            
      - name: Lint with flake8  
        run: |  
          # stop the build if there are Python syntax errors or undefined names  
          flake8 BE --count --select=E9,F63,F7,F82 --show-source --statistics  
          # exit-zero treats all errors as warnings  
          flake8 BE --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  
            
      # Uncomment if you have tests  
      # - name: Test with pytest  
      #   run: |  
      #     pytest BE/tests/  
        
      # Database migration step (using Alembic)  
      - name: Run database migrations  
        run: |  
          cd BE  
          alembic upgrade head  
        env:  
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  
          
      # Deployment step (uncomment and configure when ready)  
      # - name: Deploy to server  
      #   uses: some-deploy-action@v1  
      #   with:  
      #     source: './BE'  
      #     target: 'your-server'