name: Frontend CI/CD  
  
on:  
  push:  
    branches: [ main ]  
    paths:  
      - 'FE/**'  
  pull_request:  
    branches: [ main ]  
    paths:  
      - 'FE/**'  
  workflow_dispatch:  
  
jobs:  
  build-and-deploy:  
    runs-on: ubuntu-latest  
      
    defaults:  
      run:  
        working-directory: ./FE/automation-data-analysts  
          
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  
          
      - name: Set up Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: '19'  
          cache: 'npm'  
          cache-dependency-path: './FE/automation-data-analysts/package.json'  
            
      - name: Install dependencies  
        run: npm ci  
          
      - name: Run linting  
        run: npm run lint  
          
      - name: Build application  
        run: npm run build  
          
      - name: Upload build artifacts  
        uses: actions/upload-artifact@v3  
        with:  
          name: frontend-build  
          path: ./FE/automation-data-analysts/dist  
            
      # Deployment step (uncomment and configure when ready)  
      # - name: Deploy to hosting service  
      #   uses: some-deploy-action@v1  
      #   with:  
      #     source: './FE/automation-data-analysts/dist'  
      #     target: 'your-hosting-service'